/**
 * Regenerates `data/SCHEMA.md` from the Drizzle schema so the embedded Ask Agent always
 * has an accurate map of the SQLite cache. Run after any schema change.
 *
 * Usage:
 *   npm run gen:schema-doc            # write data/SCHEMA.md
 *   npm run gen:schema-doc -- --check # fail if data/SCHEMA.md is out of date
 */
import fs from "node:fs";
import path from "node:path";
import { is } from "drizzle-orm";
import { getTableConfig, SQLiteTable } from "drizzle-orm/sqlite-core";

const CHECK = process.argv.includes("--check");
const DATA_DIR = process.env.DATA_DIR ?? "./data";
const OUT = path.join(DATA_DIR, "SCHEMA.md");

async function buildDoc(): Promise<string> {
  let schemaMod: Record<string, unknown>;
  // Non-literal specifier so the build doesn't fail before the schema exists.
  const schemaSpecifier = "../src/db/schema.ts";
  try {
    schemaMod = (await import(schemaSpecifier)) as Record<string, unknown>;
  } catch {
    return [
      "# Database schema",
      "",
      "_Generated by `npm run gen:schema-doc`._",
      "",
      "Schema not available yet. Define `src/db/schema.ts` and re-run.",
      "",
    ].join("\n");
  }

  const out: string[] = [
    "# Database schema",
    "",
    "_Generated by `npm run gen:schema-doc`. Do not edit by hand._",
    "",
    "The local SQLite cache the Ask Agent queries via `data/query.mjs`. All timestamps are",
    "epoch milliseconds unless noted; money is stored in integer cents.",
    "",
  ];

  const tables = Object.entries(schemaMod)
    .filter(([, value]) => is(value, SQLiteTable))
    .map(([, value]) => getTableConfig(value as SQLiteTable))
    .sort((a, b) => a.name.localeCompare(b.name));

  for (const table of tables) {
    out.push(`## ${table.name}`, "");
    out.push("| column | type | null | key |");
    out.push("| --- | --- | --- | --- |");
    for (const col of table.columns) {
      const key = col.primary ? "PK" : col.isUnique ? "unique" : "";
      out.push(`| ${col.name} | ${col.getSQLType()} | ${col.notNull ? "no" : "yes"} | ${key} |`);
    }
    out.push("");
  }

  return out.join("\n");
}

async function main(): Promise<void> {
  const doc = (await buildDoc()).replace(/\s+$/, "") + "\n";
  fs.mkdirSync(DATA_DIR, { recursive: true });

  if (CHECK) {
    const existing = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
    if (existing !== doc) {
      console.error("data/SCHEMA.md is out of date. Run `npm run gen:schema-doc` and commit it.");
      process.exit(1);
    }
    console.log("gen:schema-doc --check OK");
    return;
  }

  fs.writeFileSync(OUT, doc);
  console.log(`Wrote ${OUT}`);
}

void main();
